name: PDF Build & Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Pandoc
      - uses: jgm/pandoc-action@v2
        with:
          version: 'latest'

      # Install TeX Live minimal + needed packages
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-recommended \
            texlive-latex-extra texlive-fonts-recommended \
            texlive-fonts-extra

      # Build PDF
      - name: Render PDF
        run: |
          source compile.sh

      # Check that PDF was created
      - name: Verify output
        run: test -s presentation.pdf
